id: I91A91C8D
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 14:52:46.288812
last_modified: 2023-02-08 14:52:46.288945
source_metadata:
  title: 'PP: Aṣṭasāhasrikā Prajñāpāramitā'
  language: sa
bases:
  '9225':
    base_file: 9225.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
